### ISSUE TITLE
Format contributing.md to look more professional

### ISSUE THREAD

**Issue by rcallaby** [rcallaby/cryptographic-algorithms#5]
I am looking for someone who wants to dip their toes into Open Source by contributing to my repo by formating the contributing.md file to look more professional.

This is purposely created to help those hesitant to contribute to open source projects because they may be unsure as to what to do.

This is an easy win for those that want to add to the number of repos they contribute to.

**Comment by the-amazing-atharva** [comment]
Hey!!!

I would like to work on this issue!!
Do assign me, will send you the updates in sometime 👍

**Comment by rcallaby** [comment]
Okay but please follow the guidelines in the contributing.md doc before submitting a pull request.

**Comment by rcallaby** [comment]
Okay, the issue is now closed as Atharva did such a great job.
